Dwg
Orienfish/AQI-deploy pull request #2
Opened 2020-04-30 22:49 UTC by XueyangSong

2020-05-05 01:16 UTC, Orienfish requested changes
The code is clean and looks good! I think your logic is correct, and I'm glad that you finally figured out the way to represent the clusters.
Several concerns:
1) I cannot interpret the result of DWG from the plot. Running the tutorial, I got a topology with a lot of cross-overs. Hope you could explain this on the meeting tomorrow.
2) A small suggestion on coding style. It is better to spell out the meaning of each variable, e.g. "update sensing quality matrix" rather than "update sq". For a reader, it's hard to memorize the meaning of all variables.
3) Also a suggestion on coding style. Currently the code is long. Is there some repeated processes that can be wrapped into a function and put at the end of the file? For example, for some update process (like sq, I), you can wrap them into functions. In this way, the major function will keep clean, which helps reader focus on the main flow and should be easier to understand.

2020-05-05 01:16 UTC, Orienfish commented on alg/DWG.m
> +    M = 0.0; % largest element
These initialization are not used? Perhaps you can replace them with some comments, saying what does each of them represent.

2020-05-05 01:16 UTC, Orienfish commented on alg/DWG.m
> +    %% update D, valid_idx, sq, and I matrices accordingly
Could you spell out what does each of the symbols mean in these comments?
'Cause the readers cannot memorize what does each of them mean.

2020-05-09 00:51 UTC, XueyangSong commented
I have refactored the codes as required. 
Pushed to clear stash list for easier version control.
I'll add logging information as discussed in the meeting for my next commit.

2020-05-09 22:44 UTC, closed without merging